#!/bin/sh

project_root="$1"
project_git="$project_root/.git"
pwfilter_hook=pwfilter-hook.py
hooks_to_install="pre-commit post-commit post-merge"

# find hooks directory in git repository
if [ -d "$project_git" ]; then
    hookdir="$project_git/hooks"
# if project is a submodule read .git to find actual gitdir
elif [ -f "$project_git" ]; then
    gitdir="$(awk -Fgitdir:\  '{print $NF}' $project_git)"
    hookdir="$project_root/$gitdir/hooks"
fi    

# install hooks into hooks directory
if [ -d "$hookdir" ]; then
    for h in $hooks_to_install; do
        install "$pwfilter_hook" "$hookdir/$h"
    done
fi
